stages:
  - lint
  - test

lint:
  image: registry.furqansoftware.net/cardboard/staticcheck:0.7.0-1
  stage: lint
  script:
    - task lint

test go-1.26:
  image: registry.furqansoftware.net/cardboard/golang:1.26.1-bullseye-0
  stage: test
  script:
    - task test:ci
  coverage: "/coverage: [0-9]+.[0-9]+% of statements/"
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
